# Content
title = "andrejus kostarevas"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."

# Config
theme = "hugo-alageek-theme"
baseurl = "https://andrejus.uk/"
canonifyurls = true
googleAnalytics = "UA-132770332-1"
languagecode = "en"
enableGitInfo = true
paginate = 3

# Syntax highlighting
pygmentsCodefences = true
pygmentsstyle = "vs"

# Website parameters
[params]

    # Version control
    version = "v2.12.3"
    repo = "andrejusk.github.io"
    netlify = "goofy-feynman-78d8ed"

    # Content
    subtitle = "software engineer / student"
    description = "Andrejus is a Software Engineer and Cloud Specialist, currently studying and based in Reading, UK. See his portfolio of talks, open-source projects and articles."
    copyright = "© 2019"
    copyrightUrl = "https://andrejus.uk/"
    faviconfile = "img/favicon-32x32.png"
    meta_img = "img/logo_black.png"
    logofile = "img/logo.svg"

    # Social links
    github = "andrejusk"
    twitter = "akostarevas"
    linkedin = "andrejusk"

    # Config
    noauthor = false
    enableGitInfo = "true"
    latestpostcount = 5
    highlightjs = true

# Languages
[languages]
    [languages.en]
    languageName = "English"
    weight = 1

# Menu
[menu]
    [[menu.primary]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

    [[menu.primary]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20

    [[menu.primary]]
    identifier = "talk"
    name = "Talks"
    url = "/talk/"
    weight = 30

    [[menu.primary]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

    [[menu.primary]]
    identifier = "behind-the-scenes"
    name = "BTS"
    url = "/behind-the-scenes/"
    weight = 50

    # Links
    [[menu.secondary]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/andrejusk/"
    weight = 100

    [[menu.secondary]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/akostarevas/"
    weight = 110

    [[menu.secondary]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/andrejusk/"
    weight = 120
