# Content
title = "andrejus kostarevas"
copyright = "Copyright © 2019, Andrejus Kostarevas; all rights reserved."
baseurl = "https://andrejus.uk"
googleAnalytics = "UA-132770332-1"

# Config
languagecode = "en"
canonifyurls = true
enableGitInfo = true
SectionPagesMenu = "primary"
paginate = 3

# Theme
theme = "hugo-psi-theme"
pygmentsCodefences = true
pygmentsstyle = "monokai"

# Website parameters
[params]

    # Version control
    version = "v3.0.1"
    repo = "andrejusk.github.io"

    # Content
    subtitle = "software (over-) engineer"
    description = "Andrejus is a Software Engineer and Cloud Specialist, currently studying and based in Reading, UK. See his portfolio of talks, open-source projects and articles."
    copyright = "© 2019"
    copyrightUrl = "https://github.com/andrejusk/andrejusk.github.io/blob/master/LICENSE"
    issueUrl = "https://github.com/andrejusk/andrejusk.github.io/issues/new/choose"
    faviconfile = "img/favicon-32x32.png"
    meta_img = "img/logo_black.png"
    logofile = "static/img/logo.svg"

    # Social links
    github = "andrejusk"
    twitter = "akostarevas"
    linkedin = "andrejusk"

    # Config
    noauthor = false
    enableGitInfo = "true"
    latestpostcount = 5
    highlightjs = true
    posts_navigation = true

# Menu
[menu]
    [[menu.primary]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

    [[menu.primary]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20

    [[menu.primary]]
    identifier = "talk"
    name = "Talks"
    url = "/talk/"
    weight = 30

    [[menu.primary]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

    [[menu.primary]]
    identifier = "behind-the-scenes"
    name = "BTS"
    url = "/behind-the-scenes/"
    weight = 50

[services.rss]
    limit = 20
