# Config
baseurl = "https://andrejus.uk/"
enableGitInfo = true
canonifyurls = true
paginate = 3
languagecode = "en"
pygmentsCodefences = true
pygmentsstyle = "vs"

# Content
title = "andrejus kostarevas"
theme = "hugo-alageek-theme"
googleAnalytics = "UA-132770332-1"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."

# Website parameters
[params]
    subtitle = "software engineer / student"
    description = "Andrejus is a Software Engineer and Cloud Specialist, currently studying and based in Reading, UK. See his portfolio of talks, open-source projects and articles."
    version = "v2.11.2"
    copyright = "© 2019"

    # Links
    github = "andrejusk"
    twitter = "akostarevas"
    linkedin = "andrejusk"
    repo = "andrejusk.github.io"
    netlify = "goofy-feynman-78d8ed"
    copyrightUrl = "https://andrejus.uk/"

    # Config
    noauthor = false
    enableGitInfo = "true"
    latestpostcount = 5
    faviconfile = "img/favicon-32x32.png"
    logofile = "img/logo.svg"
    highlightjs = true

# Languages
[languages]
    [languages.en]
        languageName = "English"
        weight = 1

# Featured
[[params.best_posts]]
    title = "Check out the Website Repository"
    url = "https://github.com/andrejusk/andrejusk.github.io/tree/develop"

# Menu
[[menu.primary]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.primary]]
    identifier = "talks"
    name = "Talks"
    url = "/talk/"
    weight = 20

[[menu.primary]]
    identifier = "projects"
    name = "Projects"
    url = "/project/"
    weight = 30

[[menu.primary]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[[menu.primary]]
    identifier = "bts"
    name = "BTS"
    url = "/behind-the-scenes/"
    weight = 50

# Links
[[menu.secondary]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/andrejusk/"
    weight = 100

[[menu.secondary]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/akostarevas/"
    weight = 110

[[menu.secondary]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/andrejusk/"
    weight = 120
