version: "3.7"

services:
  hugo:
    build:
      context: https://github.com/gohugoio/hugo.git#v0.62.2
      args:
        HUGO_BUILD_TAGS: extended
    command: server
    volumes:
      - type: bind
        source: ./site
        target: /site
    ports:
      - "1313:1313"
