# Netlify TOML reference
#   https://www.netlify.com/docs/netlify-toml-reference/
#
# hugo reference
#   https://gohugo.io/commands/hugo/

[build]
    publish = "public"
    command = "hugo --gc --minify --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.production.environment]
    HUGO_VERSION = "0.55"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
    command = "hugo --gc --minify -D -E -F -b $DEPLOY_PRIME_URL"

    [context.deploy-preview.environment]
        HUGO_VERSION = "0.55"
        HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
    command = "hugo --gc --minify -D -E -F -b $DEPLOY_PRIME_URL"

    [context.branch-deploy.environment]
        HUGO_VERSION = "0.55"
        HUGO_ENABLEGITINFO = "true"
